spring:
  application:
    name: product-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:0}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

---
# Product Profile
spring:
  config:
    activate:
      on-profile: prod
    import: "configserver:"

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false
